const gamingTournaments = [
    { id: 1, game: "Dota 2", tournament: "The International", prizePool: "$40M", winner: "Team Spirit" },
    { id: 2, game: "CS:GO", tournament: "PGL Major", prizePool: "$2M", winner: "Natus Vincere" },
    { id: 3, game: "Fortnite", tournament: "World Cup", prizePool: "$30M", winner: "Bugha" },
    { id: 4, game: "League of Legends", tournament: "World Championship", prizePool: "$2.34M", winner: "DWG KIA" },
    { id: 5, game: "Overwatch", tournament: "Overwatch League", prizePool: "$3.5M", winner: "San Francisco Shock" },
    { id: 6, game: "PUBG", tournament: "PUBG Global Championship", prizePool: "$4M", winner: "Gen.G Esports" },
    { id: 7, game: "Apex Legends", tournament: "ALGS Championship", prizePool: "$2M", winner: "T1" },
    { id: 8, game: "Valorant", tournament: "VCT Masters", prizePool: "$600K", winner: "Sentinels" },
    { id: 9, game: "Rocket League", tournament: "Rocket League Championship Series", prizePool: "$1.1M", winner: "Team BDS" },
    { id: 10, game: "Rainbow Six Siege", tournament: "Six Invitational", prizePool: "$3M", winner: "T1" },
    { id: 11, game: "Call of Duty", tournament: "Call of Duty League", prizePool: "$4.6M", winner: "Atlanta FaZe" },
    { id: 12, game: "FIFA", tournament: "FIFA eWorld Cup", prizePool: "$500K", winner: "Mohammed 'MoAuba' Harkous" },
    { id: 13, game: "Street Fighter V", tournament: "Capcom Cup", prizePool: "$250K", winner: "Go1" },
    { id: 14, game: "Hearthstone", tournament: "Hearthstone World Championship", prizePool: "$1M", winner: "Pavel" },
    { id: 15, game: "Smash Bros.", tournament: "EVO Championship Series", prizePool: "$200K", winner: "MkLeo" },
    { id: 16, game: "Tekken 7", tournament: "EVO Championship Series", prizePool: "$100K", winner: "Knee" },
    { id: 17, game: "Magic: The Gathering", tournament: "MTG World Championship", prizePool: "$1.5M", winner: "Paulo Vitor Damo da Rosa" },
    { id: 18, game: "StarCraft II", tournament: "StarCraft II World Championship Series", prizePool: "$700K", winner: "Serral" },
    { id: 19, game: "Dota 2", tournament: "Dota 2 Major", prizePool: "$1M", winner: "Virtus.pro" },
    { id: 20, game: "CS:GO", tournament: "CS:GO Major Championship", prizePool: "$1M", winner: "Astralis" },
    { id: 21, game: "League of Legends", tournament: "Mid-Season Invitational", prizePool: "$600K", winner: "Royal Never Give Up" },
    { id: 22, game: "PUBG Mobile", tournament: "PMPL Finals", prizePool: "$2M", winner: "Bigetron RA" },
    { id: 23, game: "FIFA", tournament: "FIFA eWorld Cup Finals", prizePool: "$500K", winner: "Mosaad 'Msdossary' Aldosary" },
    { id: 24, game: "Brawl Stars", tournament: "Brawl Stars World Finals", prizePool: "$1M", winner: "Intz Esports" },
    { id: 25, game: "Fortnite", tournament: "Fortnite Champion Series", prizePool: "$10M", winner: "Bugha" },
    { id: 26, game: "Counter-Strike", tournament: "IEM Katowice", prizePool: "$1M", winner: "Natus Vincere" },
    { id: 27, game: "Call of Duty", tournament: "Call of Duty: Modern Warfare League", prizePool: "$2M", winner: "Dallas Empire" },
    { id: 28, game: "Valorant", tournament: "VCT Champions", prizePool: "$1M", winner: "Acend" },
    { id: 29, game: "Rocket League", tournament: "RLCS World Championship", prizePool: "$1.5M", winner: "Team Vitality" },
    { id: 30, game: "Fortnite", tournament: "Fortnite World Cup Finals", prizePool: "$30M", winner: "Bugha" },
    { id: 31, game: "PUBG", tournament: "PUBG Mobile Global Championship", prizePool: "$4M", winner: "Bigetron RA" },
    { id: 32, game: "League of Legends", tournament: "League of Legends World Championship", prizePool: "$2.34M", winner: "DWG KIA" },
    { id: 33, game: "CS:GO", tournament: "DreamHack Masters", prizePool: "$250K", winner: "G2 Esports" },
    { id: 34, game: "Hearthstone", tournament: "Hearthstone Grandmasters", prizePool: "$1M", winner: "Hunterace" },
    { id: 35, game: "Valorant", tournament: "VCT Stage 2 Masters", prizePool: "$600K", winner: "Sentinels" },
    { id: 36, game: "Smash Bros.", tournament: "Smash Summit", prizePool: "$100K", winner: "Mang0" },
    { id: 37, game: "Fortnite", tournament: "FNCS Invitational", prizePool: "$5M", winner: "TBA" },
    { id: 38, game: "Rocket League", tournament: "RLCS X", prizePool: "$300K", winner: "Team BDS" },
    { id: 39, game: "CS:GO", tournament: "ESL Pro League", prizePool: "$750K", winner: "Astralis" },
    { id: 40, game: "League of Legends", tournament: "LCS Finals", prizePool: "$150K", winner: "Cloud9" },
    { id: 41, game: "Apex Legends", tournament: "ALGS Winter Circuit", prizePool: "$500K", winner: "Team Liquid" },
    { id: 42, game: "StarCraft II", tournament: "BlizzCon StarCraft II", prizePool: "$300K", winner: "INnoVation" },
    { id: 43, game: "Dota 2", tournament: "Dota 2 Asia Championship", prizePool: "$1M", winner: "LGD Gaming" },
    { id: 44, game: "FIFA", tournament: "FIFA Global Series", prizePool: "$500K", winner: "Msdossary" },
    { id: 45, game: "Street Fighter V", tournament: "EVO 2020", prizePool: "$100K", winner: "Daigo Umehara" },
    { id: 46, game: "Valorant", tournament: "VCT Stage 3 Masters", prizePool: "$1M", winner: "Sentinels" },
    { id: 47, game: "Rainbow Six Siege", tournament: "Pro League Finals", prizePool: "$200K", winner: "G2 Esports" },
    { id: 48, game: "CS:GO", tournament: "IEM Cologne", prizePool: "$1M", winner: "Astralis" },
    { id: 49, game: "League of Legends", tournament: "LPL Spring Finals", prizePool: "$100K", winner: "Royal Never Give Up" },
    { id: 50, game: "Dota 2", tournament: "ESL One", prizePool: "$1M", winner: "OG" },
    { id: 51, game: "PUBG", tournament: "PMCO Global Finals", prizePool: "$2M", winner: "BOX Gaming" },
    { id: 52, game: "Hearthstone", tournament: "Hearthstone Masters Tour", prizePool: "$250K", winner: "Seiko" },
    { id: 53, game: "Overwatch", tournament: "OWL Grand Finals", prizePool: "$1M", winner: "San Francisco Shock" },
    { id: 54, game: "Dota 2", tournament: "The Bucharest Major", prizePool: "$1M", winner: "Vici Gaming" },
    { id: 55, game: "Valorant", tournament: "VCT North America", prizePool: "$250K", winner: "Sentinels" },
    { id: 56, game: "CS:GO", tournament: "BLAST Premier", prizePool: "$750K", winner: "Vitality" },
    { id: 57, game: "Fortnite", tournament: "FNCS Grand Finals", prizePool: "$3M", winner: "Aqua" },
    { id: 58, game: "League of Legends", tournament: "LCS Spring Finals", prizePool: "$150K", winner: "Team Liquid" },
    { id: 59, game: "StarCraft II", tournament: "IEM Katowice StarCraft II", prizePool: "$400K", winner: "Serral" },
    { id: 60, game: "Dota 2", tournament: "Shanghai Major", prizePool: "$3M", winner: "Team Secret" },
    { id: 61, game: "PUBG", tournament: "Global Loot League", prizePool: "$1M", winner: "T1" },
    { id: 62, game: "Overwatch", tournament: "OWL Finals", prizePool: "$1M", winner: "San Francisco Shock" },
    { id: 63, game: "Apex Legends", tournament: "Apex Legends Global Series", prizePool: "$1M", winner: "NRG Esports" },
    { id: 64, game: "Rainbow Six Siege", tournament: "Six Invitational NA", prizePool: "$1M", winner: "TSM" },
    { id: 65, game: "FIFA", tournament: "FIFA Club World Cup", prizePool: "$500K", winner: "Team Vitality" },
  ];
  
  export default gamingTournaments;
  