const historicalEvents = [
    { id: 1, year: 1776, event: "American Revolution", significance: "Independence of the USA" },
    { id: 2, year: 1969, event: "Moon Landing", significance: "First human on the moon" },
    { id: 3, year: 1989, event: "Berlin Wall Falls", significance: "End of Cold War" },
    { id: 4, year: 1492, event: "Christopher Columbus Discovers America", significance: "European exploration of the Americas" },
    { id: 5, year: 1914, event: "World War I Begins", significance: "Global conflict between Allied and Central Powers" },
    { id: 6, year: 1945, event: "End of World War II", significance: "Victory of the Allied forces" },
    { id: 7, year: 1776, event: "Declaration of Independence", significance: "USA declares independence from Britain" },
    { id: 8, year: 1917, event: "Russian Revolution", significance: "End of Tsarist rule and rise of the Soviet Union" },
    { id: 9, year: 1963, event: "Assassination of JFK", significance: "Death of U.S. President John F. Kennedy" },
    { id: 10, year: 2001, event: "9/11 Terrorist Attacks", significance: "Terrorist attacks on the USA, leading to the War on Terror" },
    { id: 11, year: 1980, event: "Mount St. Helens Eruption", significance: "Catastrophic volcanic eruption in the U.S." },
    { id: 12, year: 1865, event: "End of the Civil War", significance: "Union victory and the abolition of slavery in the USA" },
    { id: 13, year: 1964, event: "Civil Rights Act Passed", significance: "Landmark legislation against discrimination in the USA" },
    { id: 14, year: 1912, event: "Titanic Sinks", significance: "The sinking of the RMS Titanic after hitting an iceberg" },
    { id: 15, year: 1980, event: "Election of Ronald Reagan", significance: "Ronald Reagan elected President of the United States" },
    { id: 16, year: 1947, event: "India Gains Independence", significance: "End of British colonial rule in India" },
    { id: 17, year: 1955, event: "Rosa Parks Refuses to Give Up Her Seat", significance: "Catalyst for the Civil Rights Movement in the U.S." },
    { id: 18, year: 1964, event: "The Beatles Invade America", significance: "The Beatles' first appearance on American television" },
    { id: 19, year: 1929, event: "Stock Market Crash", significance: "Start of the Great Depression in the USA" },
    { id: 20, year: 1968, event: "Martin Luther King Jr. Assassination", significance: "Death of Civil Rights Leader Martin Luther King Jr." },
    { id: 21, year: 1773, event: "Boston Tea Party", significance: "Colonial protest against British taxes" },
    { id: 22, year: 1994, event: "Nelson Mandela Elected President", significance: "End of apartheid and first black president in South Africa" },
    { id: 23, year: 1911, event: "Chinese Revolution", significance: "Overthrow of the Qing Dynasty and establishment of the Republic of China" },
    { id: 24, year: 1939, event: "World War II Begins", significance: "Start of global conflict with Nazi Germany's invasion of Poland" },
    { id: 25, year: 1954, event: "Vietnam War Begins", significance: "Start of U.S. involvement in Vietnam" },
    { id: 26, year: 1969, event: "Woodstock Festival", significance: "Iconic counterculture music festival in the U.S." },
    { id: 27, year: 1948, event: "Formation of Israel", significance: "Establishment of the state of Israel" },
    { id: 28, year: 2008, event: "Global Financial Crisis", significance: "Worldwide economic downturn caused by banking and housing crises" },
    { id: 29, year: 1991, event: "End of the Soviet Union", significance: "Collapse of the Soviet Union and independence of former Soviet states" },
    { id: 30, year: 2011, event: "Death of Osama Bin Laden", significance: "Leader of Al-Qaeda killed by U.S. Navy SEALs" },
    { id: 31, year: 1789, event: "French Revolution Begins", significance: "Overthrow of the French monarchy and rise of democratic ideals" },
    { id: 32, year: 1918, event: "End of World War I", significance: "Armistice signed ending the First World War" },
    { id: 33, year: 1944, event: "D-Day Invasion", significance: "Allied forces land in Normandy, France, to begin liberation of Western Europe" },
    { id: 34, year: 1999, event: "Y2K Scare", significance: "Global concern over potential computer glitches at the turn of the millennium" },
    { id: 35, year: 1812, event: "War of 1812", significance: "Conflict between the United States and the British Empire" },
    { id: 36, year: 1919, event: "Treaty of Versailles", significance: "End of World War I and redrawing of European borders" },
    { id: 37, year: 2016, event: "Brexit Referendum", significance: "United Kingdom votes to leave the European Union" },
    { id: 38, year: 2004, event: "Indian Ocean Tsunami", significance: "Massive natural disaster affecting multiple countries" },
    { id: 39, year: 1830, event: "July Revolution in France", significance: "Overthrow of the Bourbon monarchy in France" },
    { id: 40, year: 1981, event: "AIDS Virus Identified", significance: "Discovery of HIV/AIDS and its impact on global health" },
    { id: 41, year: 2014, event: "Annexation of Crimea by Russia", significance: "Controversial annexation of Crimea from Ukraine by Russia" },
    { id: 42, year: 1997, event: "Death of Princess Diana", significance: "Death of Princess Diana in a car crash in Paris" },
    { id: 43, year: 2010, event: "Haiti Earthquake", significance: "Devastating earthquake that affected Haiti" },
    { id: 44, year: 1962, event: "Cuban Missile Crisis", significance: "Major Cold War confrontation between the USA and USSR" },
    { id: 45, year: 1865, event: "Abraham Lincoln Assassinated", significance: "Assassination of U.S. President Abraham Lincoln after the Civil War" },
  ];
  
  export default historicalEvents;
  