const moviesSeries = [
    { id: 1, title: "Inception", genre: "Sci-Fi", rating: 8.8 },
    { id: 2, title: "Breaking Bad", genre: "Crime", rating: 9.5 },
    { id: 3, title: "Interstellar", genre: "Sci-Fi", rating: 8.6 },
    { id: 4, title: "The Dark Knight", genre: "Action", rating: 9.0 },
    { id: 5, title: "The Shawshank Redemption", genre: "Drama", rating: 9.3 },
    { id: 6, title: "The Godfather", genre: "Crime", rating: 9.2 },
    { id: 7, title: "The Matrix", genre: "Sci-Fi", rating: 8.7 },
    { id: 8, title: "The Office", genre: "Comedy", rating: 8.9 },
    { id: 9, title: "Stranger Things", genre: "Horror", rating: 8.7 },
    { id: 10, title: "Game of Thrones", genre: "Fantasy", rating: 9.3 },
    { id: 11, title: "Pulp Fiction", genre: "Crime", rating: 8.9 },
    { id: 12, title: "Forrest Gump", genre: "Drama", rating: 8.8 },
    { id: 13, title: "Fight Club", genre: "Drama", rating: 8.8 },
    { id: 14, title: "The Avengers", genre: "Action", rating: 8.0 },
    { id: 15, title: "Avengers: Endgame", genre: "Action", rating: 8.4 },
    { id: 16, title: "The Lion King", genre: "Animation", rating: 8.5 },
    { id: 17, title: "The Truman Show", genre: "Comedy", rating: 8.1 },
    { id: 18, title: "The Good Place", genre: "Comedy", rating: 8.0 },
    { id: 19, title: "Sherlock", genre: "Crime", rating: 8.8 },
    { id: 20, title: "Black Mirror", genre: "Sci-Fi", rating: 8.8 },
    { id: 21, title: "The Witcher", genre: "Fantasy", rating: 8.1 },
    { id: 22, title: "Spider-Man: No Way Home", genre: "Action", rating: 8.4 },
    { id: 23, title: "The Dark Knight Rises", genre: "Action", rating: 8.4 },
    { id: 24, title: "Inglourious Basterds", genre: "War", rating: 8.3 },
    { id: 25, title: "Joker", genre: "Drama", rating: 8.4 },
    { id: 26, title: "Star Wars: A New Hope", genre: "Sci-Fi", rating: 8.6 },
    { id: 27, title: "Guardians of the Galaxy", genre: "Action", rating: 8.0 },
    { id: 28, title: "The Mandalorian", genre: "Action", rating: 8.8 },
    { id: 29, title: "The Silence of the Lambs", genre: "Thriller", rating: 8.6 },
    { id: 30, title: "Matrix Reloaded", genre: "Sci-Fi", rating: 7.2 },
    { id: 31, title: "Mad Men", genre: "Drama", rating: 8.6 },
    { id: 32, title: "Narcos", genre: "Crime", rating: 8.8 },
    { id: 33, title: "The Sopranos", genre: "Crime", rating: 9.0 },
    { id: 34, title: "The Revenant", genre: "Adventure", rating: 8.0 },
    { id: 35, title: "The Grand Budapest Hotel", genre: "Comedy", rating: 8.1 },
    { id: 36, title: "Goodfellas", genre: "Crime", rating: 8.7 },
    { id: 37, title: "The Social Network", genre: "Drama", rating: 8.0 },
    { id: 38, title: "Pride and Prejudice", genre: "Romance", rating: 8.0 },
    { id: 39, title: "The Irishman", genre: "Crime", rating: 7.8 },
    { id: 40, title: "The Walking Dead", genre: "Horror", rating: 8.2 },
    { id: 41, title: "The Haunting of Hill House", genre: "Horror", rating: 8.6 },
    { id: 42, title: "12 Angry Men", genre: "Drama", rating: 9.0 },
    { id: 43, title: "Scarface", genre: "Crime", rating: 8.3 },
    { id: 44, title: "The Pursuit of Happyness", genre: "Drama", rating: 8.0 },
    { id: 45, title: "The Godfather Part II", genre: "Crime", rating: 9.0 },
    { id: 46, title: "The Big Bang Theory", genre: "Comedy", rating: 8.1 },
    { id: 47, title: "How I Met Your Mother", genre: "Comedy", rating: 8.3 },
    { id: 48, title: "Westworld", genre: "Sci-Fi", rating: 8.6 },
    { id: 49, title: "The Crown", genre: "Drama", rating: 8.6 },
    { id: 50, title: "The Queen's Gambit", genre: "Drama", rating: 8.6 },
  ];
  
  export default moviesSeries;
  