const spaceMissions = [
    { id: 1, agency: "NASA", mission: "Apollo 11", year: 1969, type: "Manned" },
    { id: 2, agency: "ISRO", mission: "Chandrayaan-3", year: 2023, type: "Lunar" },
    { id: 3, agency: "SpaceX", mission: "Starship Test", year: 2024, type: "Experimental" },
    { id: 4, agency: "NASA", mission: "Apollo 12", year: 1969, type: "Manned" },
    { id: 5, agency: "NASA", mission: "Apollo 13", year: 1970, type: "Manned" },
    { id: 6, agency: "NASA", mission: "Apollo 14", year: 1971, type: "Manned" },
    { id: 7, agency: "NASA", mission: "Apollo 15", year: 1971, type: "Manned" },
    { id: 8, agency: "NASA", mission: "Apollo 16", year: 1972, type: "Manned" },
    { id: 9, agency: "NASA", mission: "Apollo 17", year: 1972, type: "Manned" },
    { id: 10, agency: "NASA", mission: "Skylab", year: 1973, type: "Space Station" },
    { id: 11, agency: "NASA", mission: "Pioneer 10", year: 1972, type: "Exploration" },
    { id: 12, agency: "NASA", mission: "Pioneer 11", year: 1973, type: "Exploration" },
    { id: 13, agency: "NASA", mission: "Voyager 1", year: 1977, type: "Exploration" },
    { id: 14, agency: "NASA", mission: "Voyager 2", year: 1977, type: "Exploration" },
    { id: 15, agency: "NASA", mission: "Mariner 9", year: 1971, type: "Mars" },
    { id: 16, agency: "NASA", mission: "Mars Odyssey", year: 2001, type: "Mars Orbiter" },
    { id: 17, agency: "NASA", mission: "Mars Exploration Rover", year: 2004, type: "Mars Rover" },
    { id: 18, agency: "NASA", mission: "Curiosity Rover", year: 2012, type: "Mars Rover" },
    { id: 19, agency: "NASA", mission: "InSight Lander", year: 2018, type: "Mars Lander" },
    { id: 20, agency: "ESA", mission: "Rosetta", year: 2004, type: "Comet Exploration" },
    { id: 21, agency: "ESA", mission: "ExoMars", year: 2020, type: "Mars Rover" },
    { id: 22, agency: "ESA", mission: "Gaia", year: 2013, type: "Astrometry" },
    { id: 23, agency: "NASA", mission: "Hubble Space Telescope", year: 1990, type: "Space Telescope" },
    { id: 24, agency: "NASA", mission: "James Webb Space Telescope", year: 2021, type: "Space Telescope" },
    { id: 25, agency: "NASA", mission: "New Horizons", year: 2006, type: "Flyby" },
    { id: 26, agency: "NASA", mission: "Juno", year: 2011, type: "Jupiter Orbiter" },
    { id: 27, agency: "NASA", mission: "Cassini-Huygens", year: 1997, type: "Saturn Orbiter" },
    { id: 28, agency: "NASA", mission: "Parker Solar Probe", year: 2018, type: "Solar Probe" },
    { id: 29, agency: "NASA", mission: "Voyager 1", year: 1977, type: "Interstellar" },
    { id: 30, agency: "NASA", mission: "Mars 2020 (Perseverance Rover)", year: 2020, type: "Mars Rover" },
    { id: 31, agency: "ISRO", mission: "Chandrayaan-1", year: 2008, type: "Lunar" },
    { id: 32, agency: "ISRO", mission: "Mars Orbiter Mission (Mangalyaan)", year: 2013, type: "Mars Orbiter" },
    { id: 33, agency: "ISRO", mission: "Gaganyaan", year: 2024, type: "Manned" },
    { id: 34, agency: "SpaceX", mission: "Dragon 2", year: 2020, type: "Manned" },
    { id: 35, agency: "SpaceX", mission: "Crew Dragon", year: 2020, type: "Manned" },
    { id: 36, agency: "SpaceX", mission: "Starlink", year: 2019, type: "Satellite" },
    { id: 37, agency: "NASA", mission: "Artemis I", year: 2022, type: "Lunar" },
    { id: 38, agency: "NASA", mission: "Artemis II", year: 2024, type: "Lunar" },
    { id: 39, agency: "NASA", mission: "Artemis III", year: 2025, type: "Lunar" },
    { id: 40, agency: "NASA", mission: "Gateway", year: 2026, type: "Lunar Gateway" },
    { id: 41, agency: "NASA", mission: "Lunar Reconnaissance Orbiter", year: 2009, type: "Lunar Orbiter" },
    { id: 42, agency: "China", mission: "Chang'e 4", year: 2019, type: "Lunar" },
    { id: 43, agency: "China", mission: "Tianwen-1", year: 2021, type: "Mars Rover" },
    { id: 44, agency: "China", mission: "Tiangong", year: 2021, type: "Space Station" },
    { id: 45, agency: "China", mission: "Chang'e 5", year: 2020, type: "Lunar Sample Return" },
    { id: 46, agency: "JAXA", mission: "Hayabusa", year: 2003, type: "Asteroid Sample Return" },
    { id: 47, agency: "JAXA", mission: "Hayabusa2", year: 2014, type: "Asteroid Sample Return" },
    { id: 48, agency: "JAXA", mission: "Akasaki", year: 2025, type: "Experimental" },
    { id: 49, agency: "ESA", mission: "BepiColombo", year: 2018, type: "Mercury Orbiter" },
    { id: 50, agency: "NASA", mission: "Lunar Gateway", year: 2026, type: "Space Station" },
    { id: 51, agency: "NASA", mission: "OSIRIS-REx", year: 2016, type: "Asteroid Sample Return" },
    { id: 52, agency: "NASA", mission: "Parker Solar Probe", year: 2018, type: "Solar Probe" },
    { id: 53, agency: "NASA", mission: "TESS", year: 2018, type: "Exoplanet Search" },
    { id: 54, agency: "NASA", mission: "Kepler", year: 2009, type: "Exoplanet Search" },
    { id: 55, agency: "NASA", mission: "Spitzer Space Telescope", year: 2003, type: "Infrared Observatory" },
    { id: 56, agency: "ESA", mission: "Herschel Space Observatory", year: 2009, type: "Infrared Observatory" },
    { id: 57, agency: "ESA", mission: "LISA Pathfinder", year: 2015, type: "Gravitational Wave Observatory" },
    { id: 58, agency: "NASA", mission: "James Webb Space Telescope", year: 2021, type: "Space Telescope" },
    { id: 59, agency: "NASA", mission: "Juno", year: 2011, type: "Jupiter Orbiter" },
    { id: 60, agency: "NASA", mission: "Voyager 2", year: 1977, type: "Interstellar" },
    { id: 61, agency: "NASA", mission: "Voyager 1", year: 1977, type: "Interstellar" },
    { id: 62, agency: "NASA", mission: "Pioneer 10", year: 1972, type: "Interstellar" },
    { id: 63, agency: "NASA", mission: "Pioneer 11", year: 1973, type: "Interstellar" },
    { id: 64, agency: "NASA", mission: "Messenger", year: 2004, type: "Mercury Orbiter" },
    { id: 65, agency: "NASA", mission: "New Horizons", year: 2006, type: "Flyby" },
    { id: 66, agency: "NASA", mission: "Cassini", year: 1997, type: "Saturn Orbiter" },
    { id: 67, agency: "NASA", mission: "Hubble", year: 1990, type: "Space Telescope" },
    { id: 68, agency: "NASA", mission: "Lunar Orbiter", year: 1966, type: "Lunar Orbiter" },
    { id: 69, agency: "NASA", mission: "Mariner 10", year: 1973, type: "Mercury Orbiter" },
    { id: 70, agency: "NASA", mission: "Parker Solar Probe", year: 2018, type: "Solar Probe" },
    { id: 71, agency: "SpaceX", mission: "Falcon 9", year: 2010, type: "Launch Vehicle" },
    { id: 72, agency: "SpaceX", mission: "Falcon Heavy", year: 2018, type: "Launch Vehicle" },
    { id: 73, agency: "SpaceX", mission: "Starship", year: 2020, type: "Experimental" },
    { id: 74, agency: "SpaceX", mission: "Starship SN1", year: 2020, type: "Experimental" },
    { id: 75, agency: "NASA", mission: "Space Shuttle", year: 1981, type: "Manned" },
    { id: 76, agency: "NASA", mission: "STS-1", year: 1981, type: "Manned" },
    { id: 77, agency: "NASA", mission: "STS-2", year: 1982, type: "Manned" },
    { id: 78, agency: "NASA", mission: "STS-3", year: 1982, type: "Manned" },
    { id: 79, agency: "NASA", mission: "STS-4", year: 1982, type: "Manned" },
    { id: 80, agency: "NASA", mission: "STS-5", year: 1984, type: "Manned" },
    { id: 81, agency: "NASA", mission: "STS-6", year: 1983, type: "Manned" },
    { id: 82, agency: "NASA", mission: "STS-7", year: 1983, type: "Manned" },
    { id: 83, agency: "NASA", mission: "STS-8", year: 1983, type: "Manned" },
    { id: 84, agency: "NASA", mission: "STS-9", year: 1983, type: "Manned" },
    { id: 85, agency: "NASA", mission: "STS-10", year: 1983, type: "Manned" },
    { id: 86, agency: "NASA", mission: "STS-11", year: 1984, type: "Manned" },
    { id: 87, agency: "NASA", mission: "STS-12", year: 1984, type: "Manned" },
    { id: 88, agency: "NASA", mission: "STS-13", year: 1984, type: "Manned" },
    { id: 89, agency: "NASA", mission: "STS-14", year: 1984, type: "Manned" },
    { id: 90, agency: "NASA", mission: "STS-15", year: 1985, type: "Manned" },
    { id: 91, agency: "NASA", mission: "STS-16", year: 1985, type: "Manned" },
    { id: 92, agency: "NASA", mission: "STS-17", year: 1985, type: "Manned" },
    { id: 93, agency: "NASA", mission: "STS-18", year: 1985, type: "Manned" },
    { id: 94, agency: "NASA", mission: "STS-19", year: 1985, type: "Manned" },
    { id: 95, agency: "NASA", mission: "STS-20", year: 1985, type: "Manned" },
    { id: 96, agency: "NASA", mission: "STS-21", year: 1985, type: "Manned" },
    { id: 97, agency: "NASA", mission: "STS-22", year: 1985, type: "Manned" },
    { id: 98, agency: "NASA", mission: "STS-23", year: 1985, type: "Manned" },
    { id: 99, agency: "NASA", mission: "STS-24", year: 1985, type: "Manned" },
    { id: 100, agency: "NASA", mission: "STS-25", year: 1985, type: "Manned" },
  ];
  
  export default spaceMissions;
  